<?php

use Illuminate\Database\Seeder;

class OrganizationSeeder extends Seeder
{

    public function run()
    {
        DB::table('organizations')->insert([
            ['organization_name' =>'وزارت دفاع ملی','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'وزارت امور داخله','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'وزارت مالیه','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'وزارت عدلیه','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'وزارت امور خارجه','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'وزارت معارف','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'وزارت تحصیلات عالی','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'وزارت ارشاد، حج و اوقاف','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'وزارت انرژِی و آب','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'وزارت اطلاعات و فرهنگ','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'وزارت امور سرحدات و قبایل','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'وزارت معادن و پطرولیم','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'وزارت مخابرات و تکنالوژِی معلوماتی','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'وزارت صحت عامه','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'وزارت زراعت، آبیاری و مالداری','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'وزارت احیا و انکشاف دهات','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'وزارت مبارزه علیه مواد مخدر','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'وزارت تجارت و صنایع','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'وزارت اقتصاد','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'وزارت امور مهاجرین و عودت کنندگان','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'وزارت امور زنان','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'وزارت ترانسپورت','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'وزارت کار، امور اجتماعی ، شهدا و معلولین','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'وزارت فوائد عامه','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'وزارت شهر سازی و مسکن','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'ریاست عمومی تربیت بدنی','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'ستره محکمه','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'کمیسیون مستقل حقوق بشر افغانستان','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'جمعیت افغانی سره میاشت','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'لویه جرگه عنعنوی','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'اداره حمایه سرمایه گذاری افغانستان','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'ریاست عمومی رادیو تلویزیون ملی','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'ریاست اکادمی علوم','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'اداره مستقل هوانوردی','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'اداره مستقل انسجام امور کوچی ها','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'اداره عالی مبارزه علیه فساد اداری','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'اداره عالی تفتش','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'اداره ملی حفاظت محیط زیست','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'اداره ملی استندرد','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'اداره ملی امادگی مبارزه با حوادث','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'اداره مرکزی احصایه','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'اداره عمومی جیودیزی و کارتوگرافی','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'کمیسیون مستقل شکایات انتخاباتی','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'کميسيون مستقل انتخابات افغانستان','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'کمیسیون مستقل اصلاحات اداری و خدمات ملکی','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'کمیسیون مستقل نظارت بر تطبیق قانون اساسی','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'لوی څارنوالی','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'د افغانستان بانک','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'اداره مستقل ارگان های محل','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'اداره مستقل اراضی','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'شاروالی کابل','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'شرکت برشنا افغانستان','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'مرکز اطلاعات و رسانه های حکومت','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'ریاست عمومی اداره امور ریاست جمهوری','organization_type' =>	'داخل اداره'],
            ['organization_name' =>'ریاست دار الانشا مشرانو جرگه','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'کمیسیون برگزاری برنامه های صدمین سالگردی جشن استقلال','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'معاونیت تخنیکی','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'ریاست امور حقوقی، تقنینی و قضایی','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'ولسی جرگه','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'مشرانو جرگه','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'مشاوریت مقام عالی','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'کمیسیون عالی انرژی اتمی','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'ریاست عرایض و شکایات','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'ادارۀ عملیاتی و حمایوی انکشاف ملی ریاست جمهوری','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'ریاست عمومی محافظت ریاست جمهوری','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'ریاست دفاع و امنیت','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'ریاست عمومی امینت ملی','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'ریاست دفتر ریاست عمومی ادارۀ امور ریاست ج.ا.ا','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'شورای امنیت ملی','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'معاونیت انسجام امور دولت ریاست عمومی اداره امور ریاست جمهوری','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'اداره تنظیم خدمات مخابراتی(اترا)','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'دفتر مشاوریت ارشد ریاست جمهوری در امور زیربناها','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'دفتر مشاوریت ارشد در امور مردمی و سیاسی مقام عالی','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'اداره ملی احصائیه و معلومات','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'دفتر مشاوریت ارشد و نماینده خاص رئیس جمهور در امور انسجام ملی','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'شورای ملی','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'دفتر مشاوریت ارشد ریاست جمهوری در امور اجتماعی','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'وزارت دولت در امور پارلمانی','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'ریاست عمومی دفتر مقام عالی ریاست جمهوری','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'اداره ارتباطات عامه و استراتیژیک ریاست جمهوری','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'وزارت دولت در امور حقوق بشر و روابط بین المللی','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'جمعیت هلال احمر افغانی','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'وزارت دولت در امور رسیدگی به حوادث','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'اداره عالی بررسی','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'ریاست تعقیب تعهدات ملی و بین المللی معاونیت تخنیکی ادراه امور ریاست جمهوری','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'منابع بشری ریاست عمومی اداره امور ریاست جمهوری','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'ریاست انسجام امور مشاورین و کمیسیونهای حقیقت یاب','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'شواری طبی افغانستان','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'اداره ثبت و بررسی دارایی ها معاونیت تخنیکی اداره امور ریاست جمهوری','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'ریاست عمومی تربیت بدنی و ورزش','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'ریاست نظارت و ارزیابی معاونیت تخنیکی اداره امور ریاست جمهوری','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'ریاست امور فرهنگی و اجتماعی معاونیت روابط و آگاهی عامه ریاست عمومی اداره امور ریاست جمهوری','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'دفتر مشاور ریاست جمهوری در امور دینی و قومی','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'دفتر مشاوریت ارشد ریاست جمهوری در امور زیربناها','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'ریاست حمایت از سرمایه گذاری و انسجام پروژه های ملی معاونیت تخنیکی ریاست عمومی اداره امور ریاست جمهوری','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'ریاست مطبوعات و برنامه های معاونیت روابط و آگاهی عامه ریاست عمومی اداره امور ریاست جمهوری','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'دفتر وزیر دولت در امور شهدا و معلولین','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'ریاست امور جامعه مدنی معاونیت روابط و آگاهی عامه ریاست عمومی اداره امور ریاست جمهوی','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'ریاست عمومی شرکت آبرسانی و کانالیزاسیون شهری افغانستان','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'مشاوریت ریاست جمهوری ج.ا.ا در امور فرهنگی با ملل متحد','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'مشاوریت ریاست جمهوری ج.ا.ا در امور تقویت دموکراسی','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'ریاست امور پارلمانی و ارتباطات مردمی معاونیت روابط و آگاهی عامه','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'معاونیت اول ریاست جمهوری','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'مشاوریت ریاست جمهوری ج.ا.ا در امور عدلی و قضایی','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'اداره تدارکات ملی','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'مشاوریت ریاست جمهوری ج.ا.ا در امور اصلاح اداره','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'اداره تعلیمات تخنیکی و مسلکی','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'مشاوریت ریاست جمهوری ج.ا.ا در امور تجارتی','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'مشاوریت ریاست جمهوری ج.ا.ا در امور همبستگی اجتماعی و رفاه اقلیت ها','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'اداره مستقل زون پایتخت','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'مشاوریت ریاست جمهوری ج.ا.ا در امور حکومتداری محلی','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'مشاوریت ریاست جمهوری ج.ا.ا در امور سکتور خصوصی','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'معاونیت روابط و آگاهی عامه اداره امور ریاست جمهوری','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'وزارت دولت در امور صلح','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'معاونیت دوم ریاست جمهوری','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'کمیسیون دسترسی به اطلاعات','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'شورای عالی صلح','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'اداره هوانوردی ملکی','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'ریاست انسجام کوچی ها','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'مشاوریت مقام عالی در امور کمیسیون های اقتصادی میدان هوایی','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'مشاوریت ریاست جمهوری ج.ا.ا در امور مدارس دینی','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'مشاوریت ریاست جمهوری ج.ا.ا در امور ترانسپورت','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'اداره بازرس جمهوری اسلامی افغانستان','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'اداره انرژی هستوی','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'مشاوریت ارشد مقام عالی در امور ارتباطات عامه','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'مشاوریت ارشد مقام عالی در امور انسجام علما','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'مشاوریت ارشد مقام عالی در اموربین المللی','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'مشاوریت ارشد مقام عالی در امور صحی','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'د اریانا افغان هوایی شرکت','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'مشاوریت ارشد مقام عالی در امور مطبوعات','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'دفتر نماینده خاص رئیس جمهور در امور صلح در حوزه جنوب غرب','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'وزیر مشاور مقام عالی ریاست جمهوری در امور امنیتی','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'شورای وزیران','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'د افغانستان کرکت بورد','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'اداره ملی امتحانات','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'مشاوریت ارشد مقام عالی در امور معلولین','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'مشاوریت ارشد مقام عالی در امور فرهنگی','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'ریاست انسجام امور کابینه','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'ریاست تکنالوژی معلوماتی اداره امور ریاست جمهوری','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'ریاست عمومی انستیتوت امور قانونگذاری و تحقیقات علمی حقوقی','organization_type' =>	 'بیرون از اداره'],
            ['organization_name' =>'مشاوریت ارشد مقام عالی در امور معادن','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'مشاور ارشد مقام عالی در امور حقوقی','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'مشاوریت ارشد مقام عالی در امور اقوام و قبایل','organization_type' =>	 'داخل اداره'],
            ['organization_name' =>'اداره ملی تنظیم امور آب','organization_type' =>	 'بیرون از اداره'],

        ]);
    }
}


